default:
    title: "Ruḅick"
    zh_title: "拉比克"
    database: database.yml
    source: SRC
    # declare forms below
    form1: apple
    form2: banana
    form3: coconut # missing on purpose
    form4: guava
        
apple:
    file: a.sql
    origin: dev
    token: abcde
    description: "Minimal example."

banana:
    file: b.sql
    origin: 
    description: "Origin not set. Will not work."
    
guava:
    file: hive.sql
    origin: dbw
    token: abcde
    description: "Hive connection demo."

